### ISSUE TITLE
some rpc issues

### ISSUE THREAD

**Issue by wuminzhe** [msgport/msgscan#16]
<img width="1057" alt="image" src="https://github.com/msgport/msgscan/assets/1608576/6c07cefe-eec5-4732-87d2-302197f2dd03">

<img width="1014" alt="image" src="https://github.com/msgport/msgscan/assets/1608576/b0506dff-64fc-4dd9-9050-0b1f04a5e520">

<img width="908" alt="image" src="https://github.com/msgport/msgscan/assets/1608576/8bc34bcd-906b-4ee0-89b6-75359fde5597">

**Comment by wuminzhe** [comment]
<img width="724" alt="image" src="https://github.com/msgport/msgscan/assets/1608576/f1b3782f-186f-4a7a-ba48-9ef5a623f737">

<img width="737" alt="image" src="https://github.com/msgport/msgscan/assets/1608576/d4dfde5c-bb0a-49ae-90dd-4210f89fffeb">

**Comment by jiguantong** [comment]
Using hyperindex
