### ISSUE TITLE
Optimize the table header

### ISSUE THREAD

**Issue by jiguantong** [msgport/msgscan#49]
Msgid => Msg ID
TimeSpent => Time Spent

![image](https://github.com/msgport/msgscan/assets/27564714/8b6d9d47-c9eb-4325-92c2-ec035fd3ec91)

**Comment by boundless-forest** [comment]
![image](https://github.com/msgport/msgscan/assets/11801722/145b1c5d-e996-4013-a0a1-96e0418fe320)

I also suggest changing to `Search by Source Tx Hash/ MsgId`

**Comment by jiguantong** [comment]
> ![image](https://private-user-images.githubusercontent.com/11801722/344930035-145b1c5d-e996-4013-a0a1-96e0418fe320.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MDgwOTcsIm5iZiI6MTcxOTkwNzc5NywicGF0aCI6Ii8xMTgwMTcyMi8zNDQ5MzAwMzUtMTQ1YjFjNWQtZTk5Ni00MDEzLWEwYTEtOTZlMDQxOGZlMzIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDA4MDk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhNzFkMzU4NGIwZGMwYTU4NmI5MzM0OTM2YzU0MzBiY2M5NWY0N2Y0NmRiNTZkNTI0YzUxNjVhZTBiNjMyNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MOvDX7rwOCQdEv-Wd3PAM3R_CuM51DPPuehrVxMlS8w)
> 
> I also suggest changing to `Search by Source Tx Hash/ MsgId`


![Image](https://github.com/msgport/msgscan/assets/27564714/5632a117-0d41-4034-964e-9f9f2c8a7b66)

@snoopy1412
