### ISSUE TITLE
unknown msgport field

### ISSUE THREAD

**Issue by boundless-forest** [msgport/msgscan#5]
- https://scan.msgport.xyz/messages/0x01c885418e51a75d4c5b2983d87ef8f495d12bbf102071d710b426038b48e7c1

![image](https://github.com/msgport/msgscan/assets/11801722/195df6bc-f661-4260-adcb-a634c12fafde)

**Comment by wuminzhe** [comment]
This means that the message from dapp is start from this position. This will not exist in v2 as the v1 is not a `msgport messages scan` but a `ormp messages scan`. The `Message` here is an ormp message

**Comment by boundless-forest** [comment]
Well, it's not a good design, but solved in V2, close it.
